#!/usr/bin/bash

set -e

if [ $# -le 1 ]; then
  echo "Usage: generate_isrs.sh <isrs_gen.c> <isrs_gen.inc>"
  exit 1
fi

ISRS_GEN_C=$1
ISRS_GEN_ASM=$2

ISRS_WITH_ERROR_CODE="8 10 11 12 13 14 17 21"

# -------------C---------------------
echo "// !!! THIS FILE IS AUTOGENERATED !!!" > $ISRS_GEN_C
echo "#include <kernel/idt.h>" >> $ISRS_GEN_C
for i in $(seq 0 31); do
  echo "extern void isr${i}();" >> $ISRS_GEN_C
done
echo "void isrs_init_gates()" >> $ISRS_GEN_C
echo "{" >> $ISRS_GEN_C
for i in $(seq 0 31); do
  echo "  set_idt_gate(${i}, (unsigned int)isr${i}, 0x08, 0x8E);" >> $ISRS_GEN_C
done
echo "}" >> $ISRS_GEN_C


# ----------- ASM -----------------
echo "# !!! THIS FILE IS AUTOGENERATED !!!" > $ISRS_GEN_ASM
echo ".intel_syntax noprefix" >> $ISRS_GEN_ASM
echo ".section .text" >> $ISRS_GEN_ASM

for i in $(seq 0 31); do
  if echo "$ISRS_WITH_ERROR_CODE" | grep -q "\b${i}\b"; then
    echo "ISR_ERROR ${i}" >> $ISRS_GEN_ASM
  else
    echo "ISR_NOERROR ${i}" >> $ISRS_GEN_ASM
  fi
done
