#!/usr/bin/bash

set -e

if [ $# -le 1 ]; then
  echo "Usage: generate_isrs.sh <isrs_gen.c> <isrs_gen.inc>"
  exit 1
fi

ISRS_GEN_C=$1
ISRS_GEN_ASM=$2

ISRS_WITH_ERROR_CODE="8 10 11 12 13 14 17 21"

# -------------C---------------------
echo "// !!! THIS FILE IS AUTOGENERATED !!!" > $ISRS_GEN_C
echo "#include <kernel/idt.h>" >> $ISRS_GEN_C
for i in $(seq 0 255); do
  echo "extern void isr${i}();" >> $ISRS_GEN_C
done
echo "void isrs_init_gates()" >> $ISRS_GEN_C
echo "{" >> $ISRS_GEN_C
for i in $(seq 0 255); do
  echo "  set_idt_gate(${i}, (unsigned int)isr${i}, 0x08, 0x8E);" >> $ISRS_GEN_C
done
echo "}" >> $ISRS_GEN_C


# ----------- ASM -----------------
echo "# !!! THIS FILE IS AUTOGENERATED !!!" > $ISRS_GEN_ASM
echo ".intel_syntax noprefix" >> $ISRS_GEN_ASM
echo ".section .text" >> $ISRS_GEN_ASM
echo "" >> $ISRS_GEN_ASM
for i in $(seq 0 255); do
  echo ".global isr${i}" >> $ISRS_GEN_ASM
  echo "isr${i}:" >> $ISRS_GEN_ASM
  if echo "$ISRS_WITH_ERROR_CODE" | grep -q "\b${i}\b"; then
    echo "" >> $ISRS_GEN_ASM
  else
    echo "  push 0" >> $ISRS_GEN_ASM
  fi
  echo "  push ${i}" >> $ISRS_GEN_ASM
  echo "  jmp isr_common_stub" >> $ISRS_GEN_ASM
  echo "" >> $ISRS_GEN_ASM
done

echo "" >> $ISRS_GEN_ASM
echo ".extern fault_handler" >> $ISRS_GEN_ASM
echo "
# Common ISR stub
isr_common_stub:
  pusha

  xor eax, eax
  mov ax, ds
  push eax

  mov ax, 0x10
  mov ds, ax
  mov es, ax
  mov fs, ax
  mov gs, ax

  push esp
  call fault_handler
  add esp, 4

  pop eax
  mov ds, ax
  mov es, ax
  mov fs, ax
  mov gs, ax

  popa
  add esp, 8
  iret" >> $ISRS_GEN_ASM
